FROM node:24-slim AS build
WORKDIR /app
COPY backend/package*.json ./
RUN npm ci
COPY backend/ ./
RUN npm run build

FROM node:24-slim
WORKDIR /app
ENV NODE_ENV=production
COPY backend/package*.json ./
RUN npm ci --omit=dev
COPY --from=build /app/dist ./dist
# TODO: Cuando cree base de datos: COPY db/atlantic.db ./db/atlantic.db
EXPOSE 3000
CMD ["node", "dist/main.js"]